# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calc.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(350, 400)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_screen = QtWidgets.QLabel(self.centralwidget)
        self.label_screen.setGeometry(QtCore.QRect(0, 0, 350, 80))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_screen.setFont(font)
        self.label_screen.setStyleSheet("background-color: rgb(74, 191, 64);")
        self.label_screen.setObjectName("label_screen")
        self.btn_zeero = QtWidgets.QPushButton(self.centralwidget)
        self.btn_zeero.setGeometry(QtCore.QRect(0, 320, 150, 80))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btn_zeero.setFont(font)
        self.btn_zeero.setStyleSheet("alternate-background-color: rgb(181, 131, 90);")
        self.btn_zeero.setObjectName("btn_zeero")
        self.btn_equal = QtWidgets.QPushButton(self.centralwidget)
        self.btn_equal.setGeometry(QtCore.QRect(150, 320, 150, 80))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.btn_equal.setFont(font)
        self.btn_equal.setStyleSheet("alternate-background-color: rgb(181, 131, 90);")
        self.btn_equal.setObjectName("btn_equal")
        self.btn_one = QtWidgets.QPushButton(self.centralwidget)
        self.btn_one.setGeometry(QtCore.QRect(0, 240, 100, 80))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.btn_one.setFont(font)
        self.btn_one.setStyleSheet("alternate-background-color: rgb(181, 131, 90);")
        self.btn_one.setObjectName("btn_one")
        self.btn_three = QtWidgets.QPushButton(self.centralwidget)
        self.btn_three.setGeometry(QtCore.QRect(200, 240, 100, 80))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.btn_three.setFont(font)
        self.btn_three.setStyleSheet("alternate-background-color: rgb(181, 131, 90);")
        self.btn_three.setObjectName("btn_three")
        self.btn_two = QtWidgets.QPushButton(self.centralwidget)
        self.btn_two.setGeometry(QtCore.QRect(100, 240, 100, 80))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.btn_two.setFont(font)
        self.btn_two.setStyleSheet("alternate-background-color: rgb(181, 131, 90);")
        self.btn_two.setObjectName("btn_two")
        self.btn_six = QtWidgets.QPushButton(self.centralwidget)
        self.btn_six.setGeometry(QtCore.QRect(200, 160, 100, 80))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.btn_six.setFont(font)
        self.btn_six.setStyleSheet("alternate-background-color: rgb(181, 131, 90);")
        self.btn_six.setObjectName("btn_six")
        self.btn_five = QtWidgets.QPushButton(self.centralwidget)
        self.btn_five.setGeometry(QtCore.QRect(100, 160, 100, 80))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.btn_five.setFont(font)
        self.btn_five.setStyleSheet("alternate-background-color: rgb(181, 131, 90);")
        self.btn_five.setObjectName("btn_five")
        self.btn_thour = QtWidgets.QPushButton(self.centralwidget)
        self.btn_thour.setGeometry(QtCore.QRect(0, 160, 100, 80))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.btn_thour.setFont(font)
        self.btn_thour.setStyleSheet("alternate-background-color: rgb(181, 131, 90);")
        self.btn_thour.setObjectName("btn_thour")
        self.btn_nine = QtWidgets.QPushButton(self.centralwidget)
        self.btn_nine.setGeometry(QtCore.QRect(200, 80, 100, 80))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.btn_nine.setFont(font)
        self.btn_nine.setStyleSheet("alternate-background-color: rgb(181, 131, 90);")
        self.btn_nine.setObjectName("btn_nine")
        self.btn_eight = QtWidgets.QPushButton(self.centralwidget)
        self.btn_eight.setGeometry(QtCore.QRect(100, 80, 100, 80))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.btn_eight.setFont(font)
        self.btn_eight.setStyleSheet("alternate-background-color: rgb(181, 131, 90);")
        self.btn_eight.setObjectName("btn_eight")
        self.btn_seven = QtWidgets.QPushButton(self.centralwidget)
        self.btn_seven.setGeometry(QtCore.QRect(0, 80, 100, 80))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.btn_seven.setFont(font)
        self.btn_seven.setStyleSheet("alternate-background-color: rgb(181, 131, 90);")
        self.btn_seven.setObjectName("btn_seven")
        self.btn_plus = QtWidgets.QPushButton(self.centralwidget)
        self.btn_plus.setGeometry(QtCore.QRect(299, 80, 50, 80))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.btn_plus.setFont(font)
        self.btn_plus.setStyleSheet("alternate-background-color: rgb(181, 131, 90);")
        self.btn_plus.setObjectName("btn_plus")
        self.btn_minus = QtWidgets.QPushButton(self.centralwidget)
        self.btn_minus.setGeometry(QtCore.QRect(300, 160, 50, 80))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.btn_minus.setFont(font)
        self.btn_minus.setStyleSheet("alternate-background-color: rgb(181, 131, 90);")
        self.btn_minus.setObjectName("btn_minus")
        self.btn_multiply = QtWidgets.QPushButton(self.centralwidget)
        self.btn_multiply.setGeometry(QtCore.QRect(300, 240, 50, 80))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.btn_multiply.setFont(font)
        self.btn_multiply.setStyleSheet("alternate-background-color: rgb(181, 131, 90);")
        self.btn_multiply.setObjectName("btn_multiply")
        self.btn_divide = QtWidgets.QPushButton(self.centralwidget)
        self.btn_divide.setGeometry(QtCore.QRect(300, 320, 50, 80))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.btn_divide.setFont(font)
        self.btn_divide.setStyleSheet("alternate-background-color: rgb(181, 131, 90);")
        self.btn_divide.setObjectName("btn_divide")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.add_functions()

        self.is_equal = False



    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Калькулятор"))
        self.label_screen.setText(_translate("MainWindow", "0"))
        self.btn_zeero.setText(_translate("MainWindow", "0"))
        self.btn_equal.setText(_translate("MainWindow", "="))
        self.btn_one.setText(_translate("MainWindow", "1"))
        self.btn_three.setText(_translate("MainWindow", "3"))
        self.btn_two.setText(_translate("MainWindow", "2"))
        self.btn_six.setText(_translate("MainWindow", "6"))
        self.btn_five.setText(_translate("MainWindow", "5"))
        self.btn_thour.setText(_translate("MainWindow", "4"))
        self.btn_nine.setText(_translate("MainWindow", "9"))
        self.btn_eight.setText(_translate("MainWindow", "8"))
        self.btn_seven.setText(_translate("MainWindow", "7"))
        self.btn_plus.setText(_translate("MainWindow", "+"))
        self.btn_minus.setText(_translate("MainWindow", "-"))
        self.btn_multiply.setText(_translate("MainWindow", "*"))
        self.btn_divide.setText(_translate("MainWindow", "/"))

    def add_functions(self):
        self.btn_zeero.clicked.connect(lambda: self.write_number(self.btn_zeero.text()))
        self.btn_one.clicked.connect(lambda: self.write_number(self.btn_one.text()))
        self.btn_two.clicked.connect(lambda: self.write_number(self.btn_two.text()))
        self.btn_three.clicked.connect(lambda: self.write_number(self.btn_three.text()))
        self.btn_thour.clicked.connect(lambda: self.write_number(self.btn_thour.text()))
        self.btn_five.clicked.connect(lambda: self.write_number(self.btn_five.text()))
        self.btn_six.clicked.connect(lambda: self.write_number(self.btn_six.text()))
        self.btn_seven.clicked.connect(lambda: self.write_number(self.btn_seven.text()))
        self.btn_eight.clicked.connect(lambda: self.write_number(self.btn_eight.text()))
        self.btn_nine.clicked.connect(lambda: self.write_number(self.btn_nine.text()))
        self.btn_plus.clicked.connect(lambda: self.write_number(self.btn_plus.text()))
        self.btn_minus.clicked.connect(lambda: self.write_number(self.btn_minus.text()))
        self.btn_multiply.clicked.connect(lambda: self.write_number(self.btn_multiply.text()))
        self.btn_divide.clicked.connect(lambda: self.write_number(self.btn_divide.text()))

        self.btn_equal.clicked.connect(self.results)


    def write_number(self, number):
        if self.label_screen.text() == '0' or self.is_equal:
            self.label_screen.setText(number)
            self.is_equal = False
        else:
            self.label_screen.setText(self.label_screen.text() + number)

    def results(self):
        if self.is_equal:
            res = eval(self.label_screen.text())
            self.label_screen.setText(f'Результат равен {res}')
            self.is_equal = True
        else:
            error = QMessageBox()
            error.setWindowTitle('Ошибка')
            error.setText('Сейчас это действие выполнить нельзя')
            error.setIcon(QMessageBox.Warning)
            error.setStandardButtons(QMessageBox.Reset|QMessageBox.Ok|QMessageBox.Cancel)

            error.setInformativeText('Два разадействие не выполнить')
            error.setDetailedText('Детали')

            error.buttonClicked.connect(self.popup_action)

            error.exec_()


    def popup_action(self, btn):
        if btn.text() == 'Ok':
            print('print Ok')
        elif btn.text() == 'Reset':
            self.label_screen.setText('')
            self.is_equal = False


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())